# Generated by Django 3.1.7 on 2021-04-14 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DevilName',
            fields=[
                ('id', models.AutoField(help_text='Código do nome do capeta', primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome do capeta', max_length=255, unique=True, verbose_name='Nome')),
                ('creation_date', models.DateTimeField(auto_now_add=True, help_text='Data de criação do nome do capeta', verbose_name='Data de criação')),
            ],
            options={
                'verbose_name': 'Nome do Capeta',
                'ordering': ['name'],
            },
        ),
    ]
